### ISSUE TITLE
Dialpad/CallHistory - Tabbing too far leads to multiple component rendering

### ISSUE THREAD

**Issue by knicholsc** [star2star/react-verto-communicator#37]
Whenever a user tabs completely through a component, it gets caught in between the components and gets into a funky state displayed below:

![tabissue](https://cloud.githubusercontent.com/assets/16838772/16432765/a19f389e-3d54-11e6-886f-350de1ded8da.png)

**Comment by jschimmoeller** [comment]
![image](https://cloud.githubusercontent.com/assets/1423536/16966465/b9cab770-4dd2-11e6-9d8e-e6fada5a0336.png)

**Comment by coryschimm** [comment]
It's doing what is supposed to be doing. Just issues with # animations # at this point
