### ISSUE TITLE
errors on npm install

### ISSUE THREAD

**Issue by mjerris** [star2star/react-verto-communicator#61]
<17>:npm install
npm WARN package.json copy-webpack-plugin@3.0.1 No README data
npm WARN package.json jest-cli@12.1.1 No README data
npm WARN package.json react-intl@2.1.3 No README data
npm WARN package.json react-router@2.5.2 No README data
npm WARN package.json build@0.1.4 No README data
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer halogen@0.2.0 wants react@^0.14.8
npm ERR! peerinvalid Peer react-dom@15.2.1 wants react@^15.2.1
npm ERR! peerinvalid Peer react-intl@2.1.3 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-modal@1.4.0 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-motion@0.4.4 wants react@>=0.13.2 || ^0.14 || ^15.0.0
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer react-router@2.5.2 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer enzyme@2.4.1 wants react@0.13.x || 0.14.x || ^15.0.0-0
npm ERR! peerinvalid Peer react-addons-test-utils@15.2.1 wants react@^15.2.1

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /mnt/freeswitch/cantina/html/vcvc
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /mnt/freeswitch/cantina/html/vcvc/npm-debug.log
npm ERR! not ok code 0

**Comment by jschimmoeller** [comment]
caused by old version of node ... update node to > 4

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

**Comment by mjerris** [comment]
its even more messed up than that, and sorted now.  Just for history, on debian, you need to do that, plus
npm install -g npm

then apt-get remove nodejs 
then add a symlink to /usr/bin/npm pointing to /usr/local/bin/npm
