### ISSUE TITLE
dialpad on firefox

### ISSUE THREAD

**Issue by jschimmoeller** [star2star/react-verto-communicator#9]
open it on firefox and you will see

![image](https://cloud.githubusercontent.com/assets/1423536/15976921/a7fe07d6-2f23-11e6-988f-326580e10f21.png)

**Comment by knicholsc** [comment]
I am not currently getting this in firefox.

<img width="377" alt="screen shot 2016-06-17 at 2 54 08 pm" src="https://cloud.githubusercontent.com/assets/16838772/16161459/99e99aac-349b-11e6-9515-d38e09117449.png">
<img width="434" alt="screen shot 2016-06-17 at 2 54 29 pm" src="https://cloud.githubusercontent.com/assets/16838772/16161469/9e280df6-349b-11e6-8d34-b1c665cb2465.png">
